{
  barbarescoCollection {
    _id
    category
    _id
    nameEn
    nameUk
    nameRu
    price
    image
    imageUri {
      path
    }
    quantity
    volumeEn
    volumeUk
    volumeRu
    summaryEn
    summaryUk
    summaryRu
  }
}
